# Generated by Django 3.2.6 on 2021-12-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20211211_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymenti',
            new_name='Payment',
        ),
    ]
