# Generated by Django 3.2.6 on 2021-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_paymenti_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
