# Generated by Django 3.2.6 on 2021-12-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
