# Generated by Django 3.2.6 on 2021-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, to='cart.CartItem'),
        ),
    ]
