# Generated by Django 3.2.6 on 2021-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
