# Generated by Django 3.2.6 on 2021-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_line_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
