# Generated by Django 3.2.6 on 2021-12-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
