# Generated by Django 3.2.6 on 2021-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('featured', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('SW', 'Sports Wear'), ('S', 'shirt'), ('OW', 'Outwear')], max_length=2)),
                ('label', models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary')], max_length=1)),
                ('description', models.TextField()),
                ('quantity_available', models.IntegerField(default=1)),
            ],
        ),
    ]
