# Generated by Django 3.2.6 on 2021-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211205_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OW', 'Outwear'), ('SW', 'Sports Wear'), ('S', 'shirt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('D', 'danger'), ('P', 'primary')], max_length=1),
        ),
    ]
