# Generated by Django 3.2.6 on 2021-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211205_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'shirt'), ('SW', 'Sports Wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
